import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'th' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  th: {
    // App Brand & Topbar
    appName: 'NetMonitor',
    appSub: 'ระบบตรวจวัดและบริหารจัดการอุปกรณ์เครือข่ายและจุดกระจายสัญญาณไร้สาย',
    coreGateway: 'เกตเวย์หลัก',
    gatewayOnline: 'ออนไลน์',
    pingLatency: 'ความหน่วง',
    searchPlaceholder: 'ค้นหา อุปกรณ์, IP, MAC, VLAN หรือ SSID...',
    profile: 'โปรไฟล์',
    role: 'บทบาท',
    logout: 'ออกจากระบบ',
    switchRole: 'สลับสิทธิ์ทดสอบ',
    notifications: 'การแจ้งเตือนระบบ',
    noAlerts: 'ไม่มีการแจ้งเตือนค้างอยู่',
    viewAllAlerts: 'ดูการแจ้งเตือนทั้งหมด',

    // Roles
    roleAdmin: 'ผู้ดูแลระบบ (Admin)',
    roleEngineer: 'วิศวกรระบบ (Engineer)',
    roleViewer: 'ผู้สังเกตการณ์ (Viewer - อ่านอย่างเดียว)',

    // Navigation Menu
    navDashboard: 'แดชบอร์ดภาพรวม',
    navDevices: 'คลังอุปกรณ์เครือข่าย',
    navPorts: 'เมทริกซ์พอร์ตสวิตช์',
    navVlans: 'วิเคราะห์ทราฟฟิก VLAN',
    navAPs: 'จุดกระจายสัญญาณไร้สาย',
    navClients: 'เซสชันอุปกรณ์ลูกข่าย',
    navTopology: 'แผนผังเครือข่ายแบบโต้ตอบ',
    navAlerts: 'แจ้งเตือนเหตุการณ์ผิดปกติ',
    navEventLogs: 'บันทึกเหตุการณ์ (Syslog)',
    navStatistics: 'สถิติการใช้งานแบนด์วิดท์',
    navUsers: 'จัดการผู้ใช้งานและสิทธิ์',
    navSettings: 'ตั้งค่าระบบ',

    // Dashboard
    totalHardware: 'อุปกรณ์ฮาร์ดแวร์ทั้งหมด',
    activeNodes: 'โหนดที่ทำงานปกติ',
    disconnectedNodes: 'โหนดมีปัญหา/ตัดการเชื่อมต่อ',
    broadcastingAPs: 'จุด AP ที่กระจายสัญญาณ',
    activeClients: 'ไคลเอนต์ที่กำลังเชื่อมต่อ',
    totalThroughput: 'อัตราส่งผ่านข้อมูลรวม',
    telemetryTitle: 'การรับส่งข้อมูลแบบเรียลไทม์ (Gbps)',
    cpuMemoryTitle: 'การใช้พลังงาน CPU & RAM เฉลี่ยทั้งระบบ',
    topVlansTitle: 'ปริมาณการใช้งานทราฟฟิกแยกตาม VLAN',
    topologyPreview: 'พรีวิวแผนผังโทโพโลยี',
    viewFullTopology: 'เปิดแผนผังแบบเต็มหน้าจอ',
    criticalIncidents: 'เหตุการณ์วิกฤตที่ต้องตรวจสอบ',
    systemHealth: 'ดัชนีสุขภาพระบบ',
    nominalStatus: 'การทำงานอยู่ในเกณฑ์เสถียร',
    lastSyncTime: 'อัปเดตข้อมูลล่าสุดเมื่อ',
    refreshData: 'รีเฟรชข้อมูล',

    // Devices
    devicesInventory: 'คลังอุปกรณ์เครือข่ายทั้งหมด',
    addDevice: '+ เพิ่มอุปกรณ์ใหม่',
    deviceTypeFilter: 'ประเภทอุปกรณ์',
    statusFilter: 'สถานะ',
    allTypes: 'ทุกประเภท',
    allStatuses: 'ทุกสถานะ',
    deviceName: 'ชื่ออุปกรณ์',
    ipAddress: 'IP Address',
    type: 'ประเภท',
    modelVendor: 'รุ่น / แบรนด์',
    locationRack: 'สถานที่ติดตั้ง / ตู้แร็ค',
    uptime: 'ระยะเวลาทำงาน',
    cpuRam: 'การใช้ CPU / RAM',
    portsUp: 'พอร์ต UP / ทั้งหมด',
    actions: 'การจัดการ',
    inspectPorts: 'ดูพอร์ต',
    importConfig: 'อิมพอร์ต Config',
    editDevice: 'แก้ไข',
    deleteDevice: 'ลบ',
    readOnlyNotice: 'โหมดอ่านอย่างเดียว: ไม่สามารถแก้ไขหรือลบอุปกรณ์ได้',

    // Ports
    switchPortMatrix: 'เมทริกซ์สถานะพอร์ตสวิตช์กายภาพ',
    selectSwitch: 'เลือกสวิตช์เพื่อตรวจสอบ:',
    portStatusLegend: 'คำอธิบายสีพอร์ต:',
    portUp: 'เชื่อมต่อ (Up)',
    portDown: 'ไม่เชื่อมต่อ (Down)',
    portWarning: 'แจ้งเตือน/พบข้อผิดพลาด',
    portSfp: 'พอร์ตอัปสตรีม SFP+ 10G',
    portDetailsTitle: 'รายละเอียดพอร์ตสวิตช์',
    portInterface: 'ชื่ออินเทอร์เฟซ',
    operationalStatus: 'สถานะการทำงาน',
    negotiatedSpeed: 'ความเร็วที่เจรจาได้',
    vlanAssigned: 'VLAN ที่กำหนด',
    duplexMode: 'โหมด Duplex',
    poeDraw: 'การจ่ายไฟ PoE',
    inOutRate: 'อัตราทราฟฟิก เข้า/ออก',
    errorDiscards: 'แพ็กเก็ต Error/Discard',
    connectedMacHost: 'MAC / อุปกรณ์ที่ต่ออยู่',
    adminToggleState: 'สลับเปิด/ปิดพอร์ต (Admin State)',

    // VLANs
    vlanAnalytics: 'การตรวจสอบและวิเคราะห์ปริมาณการใช้งาน VLAN',
    addVlan: '+ เพิ่ม VLAN ใหม่',
    vlanId: 'VLAN ID',
    vlanName: 'ชื่อเครือข่าย VLAN',
    subnet: 'Subnet / CIDR',
    gateway: 'Default Gateway',
    activePortsCount: 'จำนวนพอร์ตที่ใช้งาน',
    dhcpUsage: 'การใช้งาน IP DHCP Pool',
    bandwidthUsage: 'อัตราการใช้ทราฟฟิก (Mbps)',

    // Access Points
    apClusters: 'คลัสเตอร์จุดกระจายสัญญาณไร้สาย (Wi-Fi APs)',
    apName: 'ชื่ออุปกรณ์ AP',
    ssids: 'SSID ที่กำลังกระจาย',
    channelsPower: 'แชนแนล / กำลังส่ง TX',
    avgRssi: 'ระดับสัญญาณเฉลี่ย (RSSI)',
    connectedUsers: 'ผู้ใช้งานที่เชื่อมต่อ',
    rebootAp: 'รีบูต AP',
    rebootingAp: 'กำลังส่งคำสั่งรีบูต...',
    channelOptimization: 'วิเคราะห์คลื่นและปรับจูนความถี่',

    // Clients
    activeClientSessions: 'รายการเซสชันอุปกรณ์ลูกข่าย (Read-Only)',
    clientReadonlyNotice: 'มุมมองสำหรับตรวจสอบและวิเคราะห์การใช้งานเท่านั้น (ระบบปิดการตัดการเชื่อมต่ออัตโนมัติเพื่อความปลอดภัยของระบบ)',
    hostname: 'ชื่อเครื่อง (Hostname)',
    macAddress: 'MAC Address',
    connectedNode: 'โหนดที่เชื่อมต่ออยู่',
    bandSignal: 'ย่านความถี่ / สัญญาณ (RSSI)',
    txRxRates: 'อัตรา รับ/ส่ง ข้อมูล',
    duration: 'ระยะเวลาเชื่อมต่อ',
    devicePlatform: 'ระบบปฏิบัติการ / ผู้ผลิต',

    // Topology
    interactiveTopology: 'แผนผังระบบเครือข่ายแบบโต้ตอบ (5 ระดับชั้น รองรับ 200+ โหนด)',
    editMode: 'โหมดแก้ไขแผนผัง (Edit Mode)',
    exitEditMode: 'ออกจากโหมดแก้ไข',
    saveLayout: 'บันทึกพิกัดผัง',
    layoutSaved: 'บันทึกพิกัดแผนผังลงในเครื่องเรียบร้อยแล้ว!',
    addNode: '+ เพิ่มโหนดใหม่',
    connectCable: 'เชื่อมต่อสายลิงก์',
    resetView: 'รีเซ็ตมุมมอง',
    zoomIn: 'ซูมเข้า',
    zoomOut: 'ซูมออก',
    searchNode: 'ค้นหาโหนดในผัง...',
    collapseSubtree: 'ยุบกลุ่มโหนด',
    expandSubtree: 'ขยายกลุ่มโหนด',
    hostsSubtreeCount: 'อุปกรณ์ลูกข่ายภายในกลุ่ม',
    cableType: 'ประเภทสายลิงก์',
    linkHint: 'ลากจากจุด ● ใต้อุปกรณ์ไปวางบนอุปกรณ์อื่นเพื่อเชื่อมสาย · คลิกที่สายเพื่อเปลี่ยนประเภทหรือลบ',
    linkPickTarget: 'คลิกอุปกรณ์ปลายทางเพื่อเชื่อมสาย (กด Esc เพื่อยกเลิก)',
    linkCreated: 'เชื่อมสายลิงก์เรียบร้อยแล้ว',
    linkExists: 'อุปกรณ์สองตัวนี้เชื่อมกันอยู่แล้ว',
    deleteLink: 'ลบสาย',
    viewSwitchPorts: 'ดูพอร์ตสวิตช์',

    // Alerts
    alarmIncidentDeck: 'เดสก์แจ้งเตือนเหตุการณ์และภัยคุกคามในระบบ',
    severityAll: 'ทุกระดับความรุนแรง',
    severityCritical: 'วิกฤต (Critical)',
    severityWarning: 'เตือนภัย (Warning)',
    severityInfo: 'ข้อมูล (Info)',
    alertIncident: 'เหตุการณ์ที่ตรวจพบ',
    timestamp: 'วัน-เวลาที่เกิดเหตุ',
    device: 'อุปกรณ์ต้นเหตุ',
    alertStatus: 'สถานะการจัดการ',
    acknowledgeAction: 'รับทราบเหตุ (Acknowledge)',
    acknowledgedBy: 'รับทราบโดย',
    resolveAction: 'ปิดเหตุการณ์ (Resolve)',
    ackModalTitle: 'บันทึกการรับทราบเหตุการณ์ (Incident Note)',
    ackModalPrompt: 'กรุณากรอกรายละเอียดหรือหมายเหตุการแก้ไขปัญหาเบื้องต้น:',
    ackModalPlaceholder: 'ตัวอย่าง: กำลังดำเนินการสลับสายแลนสำรอง, หรือ ส่งทีมช่างเข้าตรวจสอบตู้แร็ค...',
    ackConfirmButton: 'ยืนยันการรับทราบเหตุและบันทึกโน้ต',
    cancel: 'ยกเลิก',
    save: 'บันทึก',
    notesHistory: 'ประวัติบันทึกหมายเหตุการตรวจสอบ',

    // Syslog
    syslogTitle: 'บันทึกเหตุการณ์ระบบเครือข่าย (Syslog)',
    searchLogs: 'ค้นหาข้อความ Log, Host, IP...',
    exportLogs: 'ส่งออกข้อมูล (CSV)',
    facility: 'Facility',
    severity: 'ระดับความรุนแรง',
    hostIp: 'โฮสต์ / ไอพี',
    logMessage: 'ข้อความบันทึก',

    // Statistics
    statsTitle: 'การวิเคราะห์สถิติและการกระจายตัวของทราฟฟิก',
    trafficDistribution: 'สัดส่วนโปรโตคอลการใช้งาน',
    bandwidthTrends: 'แนวโน้มการใช้งานแบนด์วิดท์รอบ 7 วัน',
    topTalkers: 'อุปกรณ์ที่ใช้แบนด์วิดท์สูงสุด (Top Talkers)',

    // Users (Admin Only)
    userManagement: 'การจัดการผู้ใช้งานและการควบคุมสิทธิ์ (RBAC)',
    adminOnlyNote: 'เฉพาะผู้ดูแลระบบ (Admin) เท่านั้นที่สามารถจัดการผู้ใช้งานและกำหนดสิทธิ์ได้',
    createUser: '+ สร้างบัญชีผู้ใช้งานใหม่',
    userName: 'ชื่อ-นามสกุล',
    userEmail: 'อีเมลประจำตัว',
    department: 'แผนก/ฝ่าย',
    customPermissions: 'สิทธิ์การทำงานละเอียด (Permissions)',
    canEditDevices: 'แก้ไข/เพิ่ม/ลบ อุปกรณ์เครือข่าย',
    canManageUsers: 'จัดการผู้ใช้งานและสิทธิ์',
    canEditTopology: 'แก้ไขแผนผังเครือข่าย',
    canImportConfig: 'อิมพอร์ตไฟล์ Config',
    canAcknowledgeAlerts: 'รับทราบการแจ้งเตือนพร้อมใส่หมายเหตุ',
    canModifySettings: 'แก้ไขการตั้งค่าระบบและ Webhook',
    togglePassword: 'แสดง/ซ่อนรหัสผ่าน',
    statusActive: 'ใช้งานปกติ',
    statusSuspended: 'ถูกระงับสิทธิ์',

    // Settings
    settingsTitle: 'การตั้งค่าระบบ NetMonitor',
    generalSettings: 'ข้อมูลทั่วไปและการเชื่อมต่อ',
    orgName: 'ชื่อองค์กร / สถาบัน',
    pollingSettings: 'ความถี่การตรวจวัด SNMP Polling Interval',
    webhookSettings: 'ปลายทางส่งข้อความเตือน (Webhooks & Notifications)',
    slackWebhookUrl: 'Slack Webhook URL',
    telegramToken: 'Telegram Bot Token',
    telegramChatId: 'Telegram Chat ID',
    emailAlertsTo: 'อีเมลสำหรับรับข้อความแจ้งเตือนด่วน',
    testWebhook: 'ทดสอบส่งข้อความแจ้งเตือน',
    testWebhookSuccess: 'ส่งข้อความทดสอบสำเร็จเรียบร้อยแล้ว!',
    sessionTimeout: 'ระยะเวลาตัดเซสชันอัตโนมัติ (Session Timeout)',
    saveSettings: 'บันทึกการตั้งค่าระบบ',
    settingsSaved: 'บันทึกการตั้งค่าทั้งหมดเรียบร้อยแล้ว',

    // Auth Pages
    loginTitle: 'เข้าสู่ระบบ NetMonitor',
    loginSubtitle: 'ระบบบริหารจัดการและตรวจวัดโครงสร้างเครือข่ายระดับองค์กร',
    usernameOrEmail: 'ชื่อผู้ใช้ หรือ อีเมล',
    password: 'รหัสผ่าน',
    rememberMe: 'จดจำการเข้าสู่ระบบ',
    forgotPasswordLink: 'ลืมรหัสผ่าน?',
    loginButton: 'เข้าสู่ระบบ',
    noAccount: 'ยังไม่มีบัญชี?',
    registerHere: 'ลงทะเบียนใช้งานใหม่',
    registerTitle: 'สมัครสมาชิกบัญชีผู้ใช้ใหม่',
    registerSubtitle: 'ผู้ลงทะเบียนคนแรกสุดของระบบจะได้รับสิทธิ์ Admin โดยอัตโนมัติ',
    confirmPassword: 'ยืนยันรหัสผ่านอีกครั้ง',
    registerButton: 'สร้างบัญชีผู้ใช้งาน',
    haveAccount: 'มีบัญชีอยู่แล้ว?',
    loginHere: 'เข้าสู่ระบบที่นี่',
    firstUserNotice: '💡 สิทธิพิเศษ: หากคุณเป็นผู้ลงทะเบียนคนแรกในระบบ บัญชีนี้จะได้รับสิทธิ์ "Admin" สูงสุดทันที',
    
    // Forgot & Reset Password
    forgotTitle: 'กู้คืนรหัสผ่าน NetMonitor',
    forgotSubtitle: 'กรอกอีเมลที่ลงทะเบียนไว้ในระบบ เพื่อรับลิงก์และรหัส OTP กู้คืนรหัสผ่าน',
    sendResetLink: 'ส่งลิงก์กู้คืนรหัสผ่าน',
    resetEmailSent: 'รหัส OTP กู้คืนรหัสผ่านถูกส่งไปยังอีเมลของคุณเรียบร้อยแล้ว!',
    proceedToReset: 'ไปที่หน้าตั้งรหัสผ่านใหม่',
    resetTitle: 'ตั้งรหัสผ่านใหม่ (Reset Password)',
    resetSubtitle: 'กรอกรหัส OTP ยืนยันตัวตน พร้อมตั้งรหัสผ่านความปลอดภัยใหม่',
    otpCode: 'รหัสความปลอดภัย OTP (เช่น NET-849201)',
    newPassword: 'รหัสผ่านใหม่',
    confirmNewPassword: 'ยืนยันรหัสผ่านใหม่อีกครั้ง',
    submitNewPassword: 'บันทึกรหัสผ่านใหม่',
    resetSuccess: 'เปลี่ยนรหัสผ่านสำเร็จแล้ว! กรุณาเข้าสู่ระบบด้วยรหัสผ่านใหม่',
    backToLogin: 'กลับไปหน้าเข้าสู่ระบบ',
    otpExpired: 'รหัส OTP หมดอายุแล้ว (มีอายุใช้งาน 15 นาที) กรุณากดขอรหัสใหม่',
    noteRequiredError: 'กรุณากรอกรายละเอียดหรือหมายเหตุการตรวจสอบก่อนยืนยัน (ห้ามเป็นค่าว่าง)',
    linkAlreadyExists: 'มีเส้นทางการเชื่อมต่อ (Link) ระหว่างคู่อุปกรณ์นี้อยู่แล้วในระบบ',
    accessDeniedTitle: '403 - ปฏิเสธการเข้าถึง (Access Denied / Forbidden)',
    accessDeniedMessage: 'คุณไม่มีสิทธิ์การใช้งานสำหรับเข้าถึงหน้านี้ สิทธิ์ปัจจุบันของคุณ:',
    returnToDashboard: 'กลับสู่หน้าแดชบอร์ดหลัก',
    firstRegistrantBadge: 'ผู้ลงทะเบียนคนแรกจะได้รับสิทธิ์ Admin สูงสุดโดยอัตโนมัติ',
    coreInfrastructure: 'โครงสร้างพื้นฐานหลัก',
    viewerClearanceTitle: 'ระดับสิทธิ์ ผู้สังเกตการณ์ (Viewer)',
    viewerClearanceDesc: 'โหมดอ่านอย่างเดียว ล็อคการแก้ไขคอนฟิกและการกดรับทราบเหตุการณ์',
    engineerAccessTitle: 'ระดับสิทธิ์ วิศวกรเครือข่าย (Engineer)',
    engineerAccessDesc: 'สามารถจัดการอุปกรณ์และ Topology ได้ เมนูจัดการสิทธิ์ผู้ใช้ล็อคสำหรับ Admin',
    rootAdminTitle: 'ระดับสิทธิ์ ผู้ดูแลระบบสูงสุด (Root Admin)',
    rootAdminDesc: 'สิทธิ์เต็มรูปแบบ: จัดการอุปกรณ์, RBAC, แผนผังโครงข่าย และตั้งค่าระบบ',

    // Quick Test Buttons
    quickTestRoles: 'ปุ่มทดสอบสลับสิทธิ์ด่วน (Mock Login Roles):',
    loginAsAdmin: 'ทดสอบเข้าเป็น Admin',
    loginAsEngineer: 'ทดสอบเข้าเป็น Engineer',
    loginAsViewer: 'ทดสอบเข้าเป็น Viewer',
  },
  en: {
    // App Brand & Topbar
    appName: 'NetMonitor',
    appSub: 'Enterprise Network Device and Wireless Access Point Monitoring and Management System',
    coreGateway: 'Core Gateway',
    gatewayOnline: 'Online',
    pingLatency: 'Latency',
    searchPlaceholder: 'Search Devices, IPs, MACs, VLANs or SSIDs...',
    profile: 'Profile',
    role: 'Role',
    logout: 'Logout',
    switchRole: 'Quick Role Switcher',
    notifications: 'System Notifications',
    noAlerts: 'No pending critical alerts',
    viewAllAlerts: 'View all incident alerts',

    // Roles
    roleAdmin: 'Administrator (Admin)',
    roleEngineer: 'Network Engineer',
    roleViewer: 'Viewer (Read-Only)',

    // Navigation Menu
    navDashboard: 'Dashboard Overview',
    navDevices: 'Hardware Inventory',
    navPorts: 'Switch Port Matrix',
    navVlans: 'VLAN Traffic Analytics',
    navAPs: 'Wireless AP Clusters',
    navClients: 'Active Client Sessions',
    navTopology: 'Interactive Topology',
    navAlerts: 'Incident Alarm Deck',
    navEventLogs: 'Syslog Event Logs',
    navStatistics: 'Traffic Analytics',
    navUsers: 'User Management & RBAC',
    navSettings: 'System Settings',

    // Dashboard
    totalHardware: 'Total Hardware Nodes',
    activeNodes: 'Healthy Active Nodes',
    disconnectedNodes: 'Disconnected / Warnings',
    broadcastingAPs: 'Broadcasting APs',
    activeClients: 'Connected Clients',
    totalThroughput: 'Total Aggregate Throughput',
    telemetryTitle: 'Real-Time Network Telemetry (Gbps)',
    cpuMemoryTitle: 'Systemwide CPU & RAM Utilization',
    topVlansTitle: 'Top VLAN Traffic Consumption',
    topologyPreview: 'Network Topology Preview',
    viewFullTopology: 'Open Fullscreen Topology Canvas',
    criticalIncidents: 'Active Critical Incidents',
    systemHealth: 'System Health Index',
    nominalStatus: 'Operation Nominal & Resilient',
    lastSyncTime: 'Last telemetry sync at',
    refreshData: 'Refresh Telemetry',

    // Devices
    devicesInventory: 'Network Hardware Inventory',
    addDevice: '+ Add New Device',
    deviceTypeFilter: 'Device Category',
    statusFilter: 'Status',
    allTypes: 'All Categories',
    allStatuses: 'All Statuses',
    deviceName: 'Device Name',
    ipAddress: 'IP Address',
    type: 'Category',
    modelVendor: 'Vendor / Model',
    locationRack: 'Location / Rack',
    uptime: 'Uptime',
    cpuRam: 'CPU / RAM Usage',
    portsUp: 'Ports Up / Total',
    actions: 'Actions',
    inspectPorts: 'Inspect Ports',
    importConfig: 'Import Config',
    editDevice: 'Edit',
    deleteDevice: 'Delete',
    readOnlyNotice: 'Read-only mode: Modifications are restricted to Admin/Engineer.',

    // Ports
    switchPortMatrix: 'Physical Switch Port Status Matrix',
    selectSwitch: 'Select Switch Hardware:',
    portStatusLegend: 'Port Status Legend:',
    portUp: 'Active (Link Up)',
    portDown: 'Disconnected (Down)',
    portWarning: 'Error / Degradation',
    portSfp: '10G SFP+ Uplink Trunk',
    portDetailsTitle: 'Port Interface Diagnostics',
    portInterface: 'Interface Name',
    operationalStatus: 'Operational State',
    negotiatedSpeed: 'Negotiated Speed',
    vlanAssigned: 'Assigned VLAN',
    duplexMode: 'Duplex Mode',
    poeDraw: 'PoE Power Consumption',
    inOutRate: 'In / Out Traffic Rate',
    errorDiscards: 'Error & Discard Packets',
    connectedMacHost: 'Connected Device / MAC',
    adminToggleState: 'Toggle Administrative Port State',

    // VLANs
    vlanAnalytics: 'VLAN Segmentation & Bandwidth Analytics',
    addVlan: '+ Add New VLAN',
    vlanId: 'VLAN ID',
    vlanName: 'VLAN Network Name',
    subnet: 'Subnet / CIDR',
    gateway: 'Default Gateway',
    activePortsCount: 'Active Assigned Ports',
    dhcpUsage: 'DHCP Pool Saturation',
    bandwidthUsage: 'Traffic Rate (Mbps)',

    // Access Points
    apClusters: 'Enterprise Wireless Access Point Clusters',
    apName: 'AP Hostname',
    ssids: 'Broadcast SSIDs',
    channelsPower: 'Channels / TX Power',
    avgRssi: 'Average RSSI Signal',
    connectedUsers: 'Associated Clients',
    rebootAp: 'Reboot AP',
    rebootingAp: 'Dispatching reboot command...',
    channelOptimization: 'Auto RF Frequency Optimization',

    // Clients
    activeClientSessions: 'Active Client Sessions (Read-Only Inspection)',
    clientReadonlyNotice: 'Read-Only telemetry inspection view (Disconnection controls disabled to maintain critical infrastructure stability).',
    hostname: 'Hostname',
    macAddress: 'MAC Address',
    connectedNode: 'Associated Node',
    bandSignal: 'Radio Band / RSSI',
    txRxRates: 'Data Rates (Tx / Rx)',
    duration: 'Session Duration',
    devicePlatform: 'OS Platform / Vendor',

    // Topology
    interactiveTopology: 'Visual Network Topology Map (5-Tier Architecture with 200+ Nodes Support)',
    editMode: 'Topology Edit Mode',
    exitEditMode: 'Exit Edit Mode',
    saveLayout: 'Save Node Coordinates',
    layoutSaved: 'Topology coordinates successfully saved to local persistent storage!',
    addNode: '+ Add Node',
    connectCable: 'Connect Cable Link',
    resetView: 'Reset Canvas View',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    searchNode: 'Find node on canvas...',
    collapseSubtree: 'Collapse Group',
    expandSubtree: 'Expand Group',
    hostsSubtreeCount: 'Host Nodes Inside Group',
    cableType: 'Link Medium',
    linkHint: 'Drag from the ● handle under a node onto another node to connect · Click a cable to change its type or delete it',
    linkPickTarget: 'Click the destination node to connect (press Esc to cancel)',
    linkCreated: 'Cable link connected',
    linkExists: 'These two nodes are already linked',
    deleteLink: 'Delete link',
    viewSwitchPorts: 'View Switch Ports',

    // Alerts
    alarmIncidentDeck: 'System Alarm & Incident Monitoring Deck',
    severityAll: 'All Severities',
    severityCritical: 'Critical Alarm',
    severityWarning: 'Warning Alert',
    severityInfo: 'Informational',
    alertIncident: 'Detected Incident',
    timestamp: 'Occurrence Timestamp',
    device: 'Originating Device',
    alertStatus: 'Resolution State',
    acknowledgeAction: 'Acknowledge',
    acknowledgedBy: 'Acknowledged by',
    resolveAction: 'Mark Resolved',
    ackModalTitle: 'Incident Acknowledgment & Note Filing',
    ackModalPrompt: 'Provide diagnostic notes or remediation action taken:',
    ackModalPlaceholder: 'E.g., Initiated failover to secondary trunk line, dispatched field tech to inspect optic transceiver...',
    ackConfirmButton: 'Confirm Acknowledgment & Record Note',
    cancel: 'Cancel',
    save: 'Save',
    notesHistory: 'Investigation Notes & Audit Trail',

    // Syslog
    syslogTitle: 'Syslog Event & Audit Trail Stream',
    searchLogs: 'Filter Syslog message, host, IP...',
    exportLogs: 'Export Syslog (CSV)',
    facility: 'Facility',
    severity: 'Severity Level',
    hostIp: 'Source Host / IP',
    logMessage: 'Message Payload',

    // Statistics
    statsTitle: 'Longitudinal Traffic Analytics & Statistics',
    trafficDistribution: 'Protocol Bandwidth Breakdown',
    bandwidthTrends: '7-Day Cumulative Bandwidth Profile',
    topTalkers: 'Top Bandwidth Consuming Hosts',

    // Users (Admin Only)
    userManagement: 'User Management & Role-Based Access Control (RBAC)',
    adminOnlyNote: 'Restricted area: Only Administrators have clearance to modify user access and role privileges.',
    createUser: '+ Create Authorised User',
    userName: 'Full Name',
    userEmail: 'Corporate Email',
    department: 'Department',
    customPermissions: 'Granular Permissions Override',
    canEditDevices: 'Add / Edit / Delete Hardware Devices',
    canManageUsers: 'Grant User Access & Permissions',
    canEditTopology: 'Modify Topology Canvas Layout',
    canImportConfig: 'Import Running / Startup Configs',
    canAcknowledgeAlerts: 'Acknowledge Alarms with Diagnostic Notes',
    canModifySettings: 'Configure Webhooks & System Parameters',
    togglePassword: 'Show / Hide Password',
    statusActive: 'Active Access',
    statusSuspended: 'Suspended',

    // Settings
    settingsTitle: 'NetMonitor Infrastructure Configuration',
    generalSettings: 'General System & Gateway Coordinates',
    orgName: 'Organization Name',
    pollingSettings: 'SNMP & Telemetry Polling Intervals',
    webhookSettings: 'Integration Webhooks & Notification Channels',
    slackWebhookUrl: 'Slack Incoming Webhook URL',
    telegramToken: 'Telegram Bot Token',
    telegramChatId: 'Telegram Chat ID',
    emailAlertsTo: 'Urgent Dispatch Alert Email',
    testWebhook: 'Transmit Test Dispatch',
    testWebhookSuccess: 'Test dispatch successfully fired to configured webhook endpoint!',
    sessionTimeout: 'Inactivity Session Timeout',
    saveSettings: 'Commit Configuration Changes',
    settingsSaved: 'All parameters committed successfully',

    // Auth Pages
    loginTitle: 'NetMonitor Console Access',
    loginSubtitle: 'Enterprise Network Device and Wireless Access Point Monitoring Console',
    usernameOrEmail: 'Username or Email Address',
    password: 'Password',
    rememberMe: 'Keep me authenticated',
    forgotPasswordLink: 'Forgot credentials?',
    loginButton: 'Sign In to Console',
    noAccount: "Don't have an account?",
    registerHere: 'Register New Account',
    registerTitle: 'Create Console Operator Account',
    registerSubtitle: 'The initial registered user is granted Administrator (Admin) privileges automatically.',
    confirmPassword: 'Confirm Password',
    registerButton: 'Register Operator Account',
    haveAccount: 'Already registered?',
    loginHere: 'Sign In here',
    firstUserNotice: '💡 First Registrant Policy: If no users currently exist in the database, this account will automatically receive root Admin credentials.',
    
    // Forgot & Reset Password
    forgotTitle: 'Recover NetMonitor Account',
    forgotSubtitle: 'Enter your registered email address to receive an authentication OTP code and recovery instructions.',
    sendResetLink: 'Transmit Recovery OTP',
    resetEmailSent: 'Recovery OTP code has been dispatched to your email address!',
    proceedToReset: 'Proceed to Reset Password',
    resetTitle: 'Establish New Password',
    resetSubtitle: 'Input the dispatched OTP verification code and set your updated secure credentials.',
    otpCode: 'OTP Security Code (e.g., NET-849201)',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    submitNewPassword: 'Commit New Password',
    resetSuccess: 'Password has been reset successfully! You can now sign in with your new credentials.',
    backToLogin: 'Return to Sign In',
    otpExpired: 'OTP code has expired (15-minute validity ceiling). Please request a new code.',
    noteRequiredError: 'Diagnostic investigation note is mandatory (Cannot be empty or whitespace only).',
    linkAlreadyExists: 'A network link between these two nodes already exists.',
    accessDeniedTitle: '403 - Access Forbidden (Clearance Required)',
    accessDeniedMessage: 'Your operator role lacks sufficient clearance to access this module. Current clearance:',
    returnToDashboard: 'Return to Dashboard Console',
    firstRegistrantBadge: 'The initial registered user automatically receives Administrator clearance.',
    coreInfrastructure: 'Core Infrastructure',
    viewerClearanceTitle: 'Viewer Clearance',
    viewerClearanceDesc: 'Read-only mode. Configuration edits & acknowledge actions are locked.',
    engineerAccessTitle: 'Engineer Access',
    engineerAccessDesc: 'Technical ops enabled. User accounts panel is managed by Admin.',
    rootAdminTitle: 'Root Admin Clearance',
    rootAdminDesc: 'Full authority: Devices, RBAC, Topology & System Settings.',

    // Quick Test Buttons
    quickTestRoles: 'Mock RBAC Role Switcher:',
    loginAsAdmin: 'Test as Admin',
    loginAsEngineer: 'Test as Engineer',
    loginAsViewer: 'Test as Viewer',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem('netmonitor_lang');
    return (saved === 'en' || saved === 'th') ? saved : 'th';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('netmonitor_lang', newLang);
  };

  const t = (key: string): string => {
    return translations[lang][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
