import React, { useState, useEffect, useRef } from 'react';
import { useLanguage } from '../../context/LanguageContext';
import { useNetworkData } from '../../context/NetworkDataContext';
import { useAuth } from '../../context/AuthContext';
import { NetworkDevice } from '../../types';
import {
  FileCode2,
  Upload,
  X,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  ShieldAlert,
  ArrowRight,
  Split,
  FileText,
  RotateCcw,
  Sparkles,
  Server,
  Code2,
  Clock,
  Check,
  Eye,
  Sliders,
} from 'lucide-react';

interface ConfigImportModalProps {
  isOpen: boolean;
  onClose: () => void;
  targetDevice?: NetworkDevice | null;
}

// Built-in Enterprise Templates
const SAMPLE_TEMPLATES = {
  cisco_trunk: {
    name: 'Cisco IOS-XE: Enterprise 802.1Q Trunk & Voice VLAN',
    deviceType: 'Switch',
    content: `! Cisco IOS-XE Software Enterprise Switch Template
! Auto-Generated by NetMonitor Configuration Manager
hostname SW-Enterprise-Access
!
vlan 10
 name MGMT-CORP
vlan 20
 name DATA-USERS
vlan 30
 name VOICE-IP
vlan 50
 name WIFI-CORP
!
interface TenGigabitEthernet1/0/1
 description Primary Core Uplink [802.1Q Trunk]
 switchport mode trunk
 switchport trunk allowed vlan 10,20,30,50,70,100
 switchport nonegotiate
 spanning-tree guard root
!
interface range GigabitEthernet1/0/1 - 24
 description User Access Workstation & VoIP Phone
 switchport mode access
 switchport access vlan 20
 switchport voice vlan 30
 spanning-tree portfast
 spanning-tree bpduguard enable
!
end`,
  },
  cisco_ospf: {
    name: 'Cisco IOS-XE: OSPF Routing & WAN Sub-interfaces',
    deviceType: 'Router',
    content: `! Cisco IOS-XE Software WAN Router Template
hostname WAN-Edge-Gateway
!
ip routing
ip domain-lookup
!
interface GigabitEthernet0/0/0
 description Primary ISP Upstream Fiber
 ip address 203.158.0.2 255.255.255.252
 no shutdown
!
interface GigabitEthernet0/0/1
 description LAN Core Transit
 ip address 192.168.100.1 255.255.255.248
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf authentication message-digest
 ip ospf message-digest-key 1 md5 NetMonSecretKey99
 no shutdown
!
router ospf 1
 router-id 192.168.100.1
 passive-interface GigabitEthernet0/0/0
 log-adjacency-changes detail
!
line vty 0 4
 transport input ssh
 logging synchronous
!
end`,
  },
  forti_firewall: {
    name: 'Fortinet FortiOS: NGFW Security Policy & NAT Overload',
    deviceType: 'Firewall',
    content: `# FortiOS Version 7.4.2 Configuration Template
config system global
    set hostname "Perimeter-NGFW-Cluster"
    set timezone 55
end
config system interface
    edit "port1"
        set alias "WAN-Internet"
        set mode static
        set ip 192.168.100.2 255.255.255.248
        set allowaccess ping ssh https
    next
    edit "port2"
        set alias "LAN-Internal"
        set mode static
        set ip 10.10.0.254 255.255.255.0
        set allowaccess ping
    next
end
config firewall policy
    edit 101
        set name "Corp-Users-To-Internet"
        set srcintf "port2"
        set dstintf "port1"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "ALL"
        set utm-status enable
        set ssl-ssh-profile "certificate-inspection"
        set ips-sensor "default"
        set nat enable
    next
end`,
  },
  json_interface: {
    name: 'JSON Format: Interface & Policy Specification',
    deviceType: 'All',
    content: `{
  "schema": "netmonitor.config.v2",
  "device": {
    "hostname": "Core-L3-SW-01",
    "managementIp": "10.10.0.1",
    "snmpCommunity": "public_ro"
  },
  "vlans": [
    { "id": 10, "name": "MGMT", "subnet": "10.10.10.0/24", "gateway": "10.10.10.1" },
    { "id": 20, "name": "CORP-LAN", "subnet": "10.10.20.0/24", "gateway": "10.10.20.1" },
    { "id": 30, "name": "VOIP", "subnet": "10.10.30.0/24", "gateway": "10.10.30.1" },
    { "id": 50, "name": "WIFI-CORP", "subnet": "10.10.50.0/24", "gateway": "10.10.50.1" }
  ],
  "monitoring": {
    "pollingIntervalSeconds": 30,
    "flowExport": "NetFlow-v9",
    "collectorIp": "10.10.100.250"
  }
}`,
  },
};

export const ConfigImportModal: React.FC<ConfigImportModalProps> = ({
  isOpen,
  onClose,
  targetDevice,
}) => {
  const { t, lang } = useLanguage();
  const { devices, importDeviceConfig } = useNetworkData();
  const { currentUser, isViewer } = useAuth();

  const [selectedDeviceId, setSelectedDeviceId] = useState<string>(
    targetDevice?.id || devices[0]?.id || ''
  );
  const [configContent, setConfigContent] = useState<string>('');
  const [fileName, setFileName] = useState<string>('');
  const [fileSize, setFileSize] = useState<number>(0);
  const [isDragging, setIsDragging] = useState(false);
  const [activeTab, setActiveTab] = useState<'editor' | 'diff'>('editor');

  // Options
  const [deploymentMode, setDeploymentMode] = useState<'merge' | 'replace'>('merge');
  const [enableRollback, setEnableRollback] = useState(true);
  const [changeNote, setChangeNote] = useState('');

  // Validation State
  const [validationResult, setValidationResult] = useState<{
    status: 'idle' | 'valid' | 'warning' | 'error';
    messages: { type: 'error' | 'warning' | 'info'; text: string; line?: number }[];
  }>({ status: 'idle', messages: [] });

  // Deployment progress
  const [isDeploying, setIsDeploying] = useState(false);
  const [deploySuccess, setDeploySuccess] = useState(false);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Sync selected device
  useEffect(() => {
    if (targetDevice) {
      setSelectedDeviceId(targetDevice.id);
    } else if (devices.length > 0 && !selectedDeviceId) {
      setSelectedDeviceId(devices[0].id);
    }
  }, [targetDevice, devices]);

  // When selected device changes, if no custom config loaded, initialize with running config or hint
  const currentDevice = devices.find(d => d.id === selectedDeviceId);

  useEffect(() => {
    if (currentDevice && !configContent) {
      setConfigContent(
        currentDevice.config ||
          `! Running configuration for ${currentDevice.name} [${currentDevice.ip}]\n! Vendor: ${currentDevice.vendor} ${currentDevice.model}\nhostname ${currentDevice.name}\n!\nend`
      );
    }
  }, [currentDevice]);

  if (!isOpen) return null;

  // Handle Drag & Drop
  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  };

  const processFile = (file: File) => {
    if (!file) return;
    setFileName(file.name);
    setFileSize(file.size);

    const reader = new FileReader();
    reader.onload = ev => {
      const text = ev.target?.result as string;
      if (text) {
        setConfigContent(text);
        runSyntaxValidation(text);
      }
    };
    reader.readAsText(file);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files?.[0];
    if (file) {
      processFile(file);
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      processFile(file);
    }
  };

  // Run comprehensive syntax & security validation
  const runSyntaxValidation = (content: string = configContent) => {
    const lines = content.split('\n');
    const messages: { type: 'error' | 'warning' | 'info'; text: string; line?: number }[] = [];
    let hasError = false;
    let hasWarning = false;

    if (!content.trim()) {
      setValidationResult({
        status: 'error',
        messages: [{ type: 'error', text: 'Configuration payload is empty' }],
      });
      return;
    }

    // Check JSON if content starts with {
    if (content.trim().startsWith('{')) {
      try {
        JSON.parse(content);
        messages.push({
          type: 'info',
          text: 'Valid JSON syntax confirmed. Complies with NetMonitor schema v2.',
        });
      } catch (err: any) {
        hasError = true;
        messages.push({
          type: 'error',
          text: `JSON Parse Syntax Error: ${err.message}`,
        });
      }
    } else {
      // CLI / Cisco / Fortinet / Aruba syntax checks
      let foundHostname = false;
      let openBlocks = 0;

      lines.forEach((rawLine, idx) => {
        const line = rawLine.trim();
        const lineNum = idx + 1;

        if (line.toLowerCase().startsWith('hostname ') || line.toLowerCase().startsWith('set hostname')) {
          foundHostname = true;
        }

        // Security check: Unencrypted telnet
        if (line.toLowerCase().includes('transport input telnet') || line.toLowerCase().includes('telnet enable')) {
          hasWarning = true;
          messages.push({
            type: 'warning',
            line: lineNum,
            text: 'Security Warning: Insecure plaintext Telnet protocol detected. Prefer SSHv2.',
          });
        }

        // Security check: Plaintext password
        if (line.toLowerCase().startsWith('password ') && !line.toLowerCase().includes('7 ') && !line.toLowerCase().includes('secret ')) {
          hasWarning = true;
          messages.push({
            type: 'warning',
            line: lineNum,
            text: 'Security Warning: Plaintext password without encryption hash. Recommend "service password-encryption" or "enable secret".',
          });
        }

        // Security check: Insecure HTTP web GUI
        if (line.toLowerCase().startsWith('ip http server') && !line.toLowerCase().includes('secure')) {
          hasWarning = true;
          messages.push({
            type: 'warning',
            line: lineNum,
            text: 'Security Advisory: Unencrypted HTTP web management active. Prefer "ip http secure-server".',
          });
        }

        // Check for common malformed IP pattern
        const ipMatch = line.match(/\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/g);
        if (ipMatch) {
          ipMatch.forEach(ip => {
            const octets = ip.split('.').map(Number);
            if (octets.some(o => o < 0 || o > 255)) {
              hasError = true;
              messages.push({
                type: 'error',
                line: lineNum,
                text: `Syntax Error: Invalid IP octet value (${ip}) outside 0-255 range.`,
              });
            }
          });
        }

        // Check block balance for FortiOS
        if (line.startsWith('config ') || line.startsWith('edit ')) openBlocks++;
        if (line === 'end' || line === 'next') openBlocks = Math.max(0, openBlocks - 1);
      });

      if (!foundHostname) {
        messages.push({
          type: 'warning',
          text: 'Notice: No "hostname" directive defined in script. Device will retain previous name.',
        });
        hasWarning = true;
      }

      if (openBlocks > 0) {
        messages.push({
          type: 'warning',
          text: `Warning: ${openBlocks} unclosed configuration block(s) detected (missing 'end' or 'next').`,
        });
        hasWarning = true;
      }

      if (!hasError && !hasWarning) {
        messages.push({
          type: 'info',
          text: 'CLI command structure validated. Interfaces, subnets, and credentials syntax passed.',
        });
      }
    }

    setValidationResult({
      status: hasError ? 'error' : hasWarning ? 'warning' : 'valid',
      messages,
    });
  };

  // Compute visual line-by-line diff between current running config & new proposed config
  const computeDiff = () => {
    const running = (currentDevice?.config || '').split('\n');
    const proposed = configContent.split('\n');

    const runningSet = new Set(running.map(l => l.trim()));
    const proposedSet = new Set(proposed.map(l => l.trim()));

    const diffLines: {
      type: 'added' | 'removed' | 'unchanged';
      content: string;
      lineNum?: number;
    }[] = [];

    // Removed lines (in running but not in proposed if replace mode)
    if (deploymentMode === 'replace') {
      running.forEach((line, idx) => {
        const trimmed = line.trim();
        if (trimmed && !proposedSet.has(trimmed)) {
          diffLines.push({ type: 'removed', content: line, lineNum: idx + 1 });
        }
      });
    }

    // Lines in proposed
    proposed.forEach((line, idx) => {
      const trimmed = line.trim();
      if (trimmed && !runningSet.has(trimmed)) {
        diffLines.push({ type: 'added', content: line, lineNum: idx + 1 });
      } else {
        diffLines.push({ type: 'unchanged', content: line, lineNum: idx + 1 });
      }
    });

    const addedCount = diffLines.filter(d => d.type === 'added').length;
    const removedCount = diffLines.filter(d => d.type === 'removed').length;

    return { diffLines, addedCount, removedCount };
  };

  const { diffLines, addedCount, removedCount } = computeDiff();

  // Load sample template
  const handleLoadTemplate = (key: keyof typeof SAMPLE_TEMPLATES) => {
    const tpl = SAMPLE_TEMPLATES[key];
    setConfigContent(tpl.content);
    setFileName(`template_${key}.cfg`);
    setFileSize(tpl.content.length);
    runSyntaxValidation(tpl.content);
  };

  // Apply & Deploy configuration
  const handleDeploy = async () => {
    if (!currentDevice) return;
    if (isViewer) {
      alert('Access Denied: Viewer accounts have read-only privileges.');
      return;
    }

    setIsDeploying(true);

    // Simulate connection and checksum transmission
    setTimeout(() => {
      const author = currentUser ? `${currentUser.name} (${currentUser.role})` : 'Operator';
      importDeviceConfig(
        currentDevice.id,
        configContent,
        deploymentMode,
        enableRollback,
        author
      );

      setIsDeploying(false);
      setDeploySuccess(true);

      setTimeout(() => {
        setDeploySuccess(false);
        onClose();
      }, 1800);
    }, 1200);
  };

  const totalLines = configContent ? configContent.split('\n').length : 0;
  const totalChars = configContent.length;

  return (
    <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-md z-50 flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl max-w-4xl w-full shadow-2xl overflow-hidden flex flex-col max-h-[92vh]">
        {/* Header */}
        <div className="px-6 py-4 bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 text-white flex items-center justify-between border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-cyan-500/20 border border-cyan-500/30 flex items-center justify-center text-cyan-400">
              <FileCode2 className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold flex items-center gap-2">
                <span>{t('configImportTitle')}</span>
                <span className="text-[11px] px-2 py-0.5 rounded-full bg-cyan-950 border border-cyan-700 text-cyan-300 font-mono font-medium">
                  v2.4 Engine
                </span>
              </h2>
              <p className="text-xs text-slate-400">{t('configImportSub')}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Success Alert Banner */}
        {deploySuccess && (
          <div className="p-4 bg-emerald-950/90 border-b border-emerald-700 text-emerald-200 text-xs flex items-center justify-between animate-fadeIn">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-emerald-400 animate-bounce" />
              <span className="font-semibold">{t('deploySuccess')}</span>
            </div>
            <span className="font-mono text-[11px] text-emerald-300">
              Device: {currentDevice?.name} ({currentDevice?.ip})
            </span>
          </div>
        )}

        <div className="p-5 overflow-y-auto space-y-4 flex-1">
          {/* Row 1: Target Device Selector & Sample Templates */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Device Selector */}
            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 flex items-center gap-1.5">
                <Server className="w-3.5 h-3.5 text-cyan-500" />
                <span>{t('selectTargetDevice')}</span>
                <span className="text-rose-500">*</span>
              </label>
              <select
                value={selectedDeviceId}
                onChange={e => setSelectedDeviceId(e.target.value)}
                className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl px-3 py-2 text-xs text-slate-900 dark:text-white font-medium focus:outline-none focus:ring-2 focus:ring-cyan-500"
              >
                {devices.map(d => (
                  <option key={d.id} value={d.id}>
                    [{d.type}] {d.name} — {d.ip} ({d.vendor})
                  </option>
                ))}
              </select>

              {currentDevice && (
                <div className="flex items-center gap-3 text-[11px] text-slate-500 dark:text-slate-400 font-mono px-1">
                  <span>Vendor: {currentDevice.vendor}</span>
                  <span>•</span>
                  <span>Model: {currentDevice.model}</span>
                  <span>•</span>
                  <span className="text-emerald-500 font-semibold uppercase">{currentDevice.status}</span>
                </div>
              )}
            </div>

            {/* Quick Sample Templates */}
            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-amber-500" />
                <span>{t('loadSampleTemplate')}</span>
              </label>
              <div className="grid grid-cols-2 gap-1.5">
                <button
                  type="button"
                  onClick={() => handleLoadTemplate('cisco_trunk')}
                  className="px-2.5 py-1.5 text-left rounded-lg bg-slate-100 dark:bg-slate-800 hover:bg-cyan-50 dark:hover:bg-cyan-950/40 hover:border-cyan-400 border border-slate-200 dark:border-slate-700 text-[11px] text-slate-700 dark:text-slate-300 truncate transition-colors"
                >
                  ⚡ {t('templateCiscoTrunk')}
                </button>
                <button
                  type="button"
                  onClick={() => handleLoadTemplate('cisco_ospf')}
                  className="px-2.5 py-1.5 text-left rounded-lg bg-slate-100 dark:bg-slate-800 hover:bg-cyan-50 dark:hover:bg-cyan-950/40 hover:border-cyan-400 border border-slate-200 dark:border-slate-700 text-[11px] text-slate-700 dark:text-slate-300 truncate transition-colors"
                >
                  ⚡ {t('templateCiscoOspf')}
                </button>
                <button
                  type="button"
                  onClick={() => handleLoadTemplate('forti_firewall')}
                  className="px-2.5 py-1.5 text-left rounded-lg bg-slate-100 dark:bg-slate-800 hover:bg-cyan-50 dark:hover:bg-cyan-950/40 hover:border-cyan-400 border border-slate-200 dark:border-slate-700 text-[11px] text-slate-700 dark:text-slate-300 truncate transition-colors"
                >
                  ⚡ {t('templateFortiPolicy')}
                </button>
                <button
                  type="button"
                  onClick={() => handleLoadTemplate('json_interface')}
                  className="px-2.5 py-1.5 text-left rounded-lg bg-slate-100 dark:bg-slate-800 hover:bg-cyan-50 dark:hover:bg-cyan-950/40 hover:border-cyan-400 border border-slate-200 dark:border-slate-700 text-[11px] text-slate-700 dark:text-slate-300 truncate transition-colors"
                >
                  ⚡ {t('templateJsonConfig')}
                </button>
              </div>
            </div>
          </div>

          {/* Drag & Drop File Upload Area */}
          <div
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            onClick={() => fileInputRef.current?.click()}
            className={`border-2 border-dashed rounded-xl p-4 text-center cursor-pointer transition-all ${
              isDragging
                ? 'border-cyan-500 bg-cyan-500/10'
                : 'border-slate-300 dark:border-slate-700 hover:border-cyan-400 dark:hover:border-cyan-500 bg-slate-50/50 dark:bg-slate-800/40'
            }`}
          >
            <input
              ref={fileInputRef}
              type="file"
              accept=".cfg,.txt,.json,.conf,.text"
              onChange={handleFileChange}
              className="hidden"
            />
            <div className="flex flex-col items-center justify-center gap-1.5">
              <div className="w-8 h-8 rounded-full bg-cyan-500/10 dark:bg-cyan-500/20 text-cyan-600 dark:text-cyan-400 flex items-center justify-center">
                <Upload className="w-4 h-4" />
              </div>
              <div className="text-xs font-semibold text-slate-800 dark:text-slate-200">
                {fileName ? (
                  <span className="text-cyan-600 dark:text-cyan-400 flex items-center gap-1.5">
                    <FileText className="w-3.5 h-3.5" />
                    {fileName} ({(fileSize / 1024).toFixed(1)} KB)
                  </span>
                ) : (
                  t('dragDropFile')
                )}
              </div>
              <p className="text-[11px] text-slate-500 dark:text-slate-400">
                {t('dragDropSub')}
              </p>
            </div>
          </div>

          {/* View Mode Toggle: Script Editor vs Visual Diff */}
          <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-2">
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => setActiveTab('editor')}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors ${
                  activeTab === 'editor'
                    ? 'bg-cyan-600 text-white shadow-xs'
                    : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200'
                }`}
              >
                <Code2 className="w-3.5 h-3.5" />
                <span>{t('configEditor')}</span>
              </button>
              <button
                type="button"
                onClick={() => setActiveTab('diff')}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors ${
                  activeTab === 'diff'
                    ? 'bg-cyan-600 text-white shadow-xs'
                    : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200'
                }`}
              >
                <Split className="w-3.5 h-3.5" />
                <span>{t('compareDiff')}</span>
                {(addedCount > 0 || removedCount > 0) && (
                  <span className="text-[10px] px-1.5 py-0.2 rounded-full bg-slate-900 text-cyan-300 font-mono">
                    +{addedCount} / -{removedCount}
                  </span>
                )}
              </button>
            </div>

            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => runSyntaxValidation(configContent)}
                className="px-2.5 py-1 rounded-lg bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 text-xs font-medium border border-slate-200 dark:border-slate-700 flex items-center gap-1.5"
              >
                <ShieldAlert className="w-3.5 h-3.5 text-cyan-500" />
                <span>{t('syntaxValidation')}</span>
              </button>
              <span className="text-[11px] text-slate-400 font-mono">
                {totalLines} lines • {totalChars} chars
              </span>
            </div>
          </div>

          {/* Validation Status Feedback Banner */}
          {validationResult.status !== 'idle' && (
            <div
              className={`p-3 rounded-xl border text-xs space-y-1.5 ${
                validationResult.status === 'valid'
                  ? 'bg-emerald-50 dark:bg-emerald-950/40 border-emerald-300 dark:border-emerald-800 text-emerald-800 dark:text-emerald-300'
                  : validationResult.status === 'warning'
                  ? 'bg-amber-50 dark:bg-amber-950/40 border-amber-300 dark:border-amber-800 text-amber-800 dark:text-amber-300'
                  : 'bg-rose-50 dark:bg-rose-950/40 border-rose-300 dark:border-rose-800 text-rose-800 dark:text-rose-300'
              }`}
            >
              <div className="flex items-center gap-2 font-semibold">
                {validationResult.status === 'valid' ? (
                  <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                ) : validationResult.status === 'warning' ? (
                  <AlertTriangle className="w-4 h-4 text-amber-500" />
                ) : (
                  <XCircle className="w-4 h-4 text-rose-500" />
                )}
                <span>
                  {validationResult.status === 'valid'
                    ? t('syntaxValid')
                    : validationResult.status === 'warning'
                    ? t('syntaxWarning')
                    : t('syntaxError')}
                </span>
              </div>
              <ul className="list-disc list-inside space-y-0.5 text-[11px] pl-1 font-mono">
                {validationResult.messages.map((m, idx) => (
                  <li key={idx}>
                    {m.line && <span className="font-bold underline mr-1">Line {m.line}:</span>}
                    {m.text}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Content Area: Tab 1 = Editor */}
          {activeTab === 'editor' && (
            <div className="relative rounded-xl border border-slate-800 overflow-hidden bg-slate-950 shadow-inner">
              <div className="flex items-center justify-between px-3 py-1.5 bg-slate-900 border-b border-slate-800 text-[11px] text-slate-400 font-mono">
                <span>CLI Terminal Running-Config Editor</span>
                <span>Encoding: UTF-8 (Unix LF)</span>
              </div>
              <div className="flex">
                {/* Line Numbers */}
                <div className="w-10 py-3 bg-slate-900/60 text-slate-600 font-mono text-xs select-none text-right pr-2 space-y-0.5 border-r border-slate-800">
                  {Array.from({ length: Math.max(1, totalLines) }).map((_, i) => (
                    <div key={i} className="leading-5">
                      {i + 1}
                    </div>
                  ))}
                </div>
                {/* Textarea */}
                <textarea
                  value={configContent}
                  onChange={e => {
                    setConfigContent(e.target.value);
                    if (validationResult.status !== 'idle') {
                      runSyntaxValidation(e.target.value);
                    }
                  }}
                  rows={13}
                  spellCheck={false}
                  placeholder="! Paste startup-config or running-config commands here..."
                  className="flex-1 bg-transparent text-emerald-400 font-mono text-xs p-3 focus:outline-none leading-5 resize-none selection:bg-cyan-800/60"
                ></textarea>
              </div>
            </div>
          )}

          {/* Content Area: Tab 2 = Visual Diff */}
          {activeTab === 'diff' && (
            <div className="rounded-xl border border-slate-800 overflow-hidden bg-slate-950 font-mono text-xs">
              <div className="flex items-center justify-between px-3 py-2 bg-slate-900 border-b border-slate-800 text-[11px]">
                <span className="text-slate-300 font-semibold">{t('diffModeTitle')}</span>
                <div className="flex items-center gap-3">
                  <span className="text-emerald-400 font-medium">+{addedCount} additions</span>
                  <span className="text-rose-400 font-medium">-{removedCount} removals</span>
                </div>
              </div>
              <div className="max-h-[300px] overflow-y-auto p-2 space-y-0.5">
                {diffLines.length === 0 ? (
                  <div className="text-slate-500 text-center py-8">
                    No configuration differences detected. New config is identical to running config.
                  </div>
                ) : (
                  diffLines.map((line, idx) => (
                    <div
                      key={idx}
                      className={`flex items-start px-2 py-0.5 rounded leading-5 ${
                        line.type === 'added'
                          ? 'bg-emerald-950/50 text-emerald-300 border-l-2 border-emerald-500'
                          : line.type === 'removed'
                          ? 'bg-rose-950/50 text-rose-300 border-l-2 border-rose-500'
                          : 'text-slate-400'
                      }`}
                    >
                      <span className="w-8 select-none text-slate-600 text-[10px] text-right pr-2">
                        {line.lineNum || ''}
                      </span>
                      <span className="w-4 select-none font-bold">
                        {line.type === 'added' ? '+' : line.type === 'removed' ? '-' : ' '}
                      </span>
                      <span className="flex-1 whitespace-pre-wrap">{line.content}</span>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}

          {/* Deployment Strategy & Options */}
          <div className="bg-slate-50 dark:bg-slate-800/60 p-4 rounded-xl border border-slate-200 dark:border-slate-700/80 space-y-3">
            <h4 className="text-xs font-bold text-slate-800 dark:text-slate-200 flex items-center gap-1.5">
              <Sliders className="w-3.5 h-3.5 text-cyan-500" />
              <span>{t('deploymentMode')}</span>
            </h4>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              <label
                className={`flex items-start gap-2.5 p-2.5 rounded-lg border cursor-pointer transition-all ${
                  deploymentMode === 'merge'
                    ? 'border-cyan-500 bg-cyan-50 dark:bg-cyan-950/30'
                    : 'border-slate-200 dark:border-slate-700'
                }`}
              >
                <input
                  type="radio"
                  name="deployMode"
                  checked={deploymentMode === 'merge'}
                  onChange={() => setDeploymentMode('merge')}
                  className="mt-0.5 text-cyan-600 focus:ring-cyan-500"
                />
                <div>
                  <span className="font-semibold text-slate-800 dark:text-slate-200">
                    {t('modeMerge')}
                  </span>
                  <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5">
                    Preserves current interfaces and VLANs, updating only configured statements.
                  </p>
                </div>
              </label>

              <label
                className={`flex items-start gap-2.5 p-2.5 rounded-lg border cursor-pointer transition-all ${
                  deploymentMode === 'replace'
                    ? 'border-rose-500 bg-rose-50 dark:bg-rose-950/30'
                    : 'border-slate-200 dark:border-slate-700'
                }`}
              >
                <input
                  type="radio"
                  name="deployMode"
                  checked={deploymentMode === 'replace'}
                  onChange={() => setDeploymentMode('replace')}
                  className="mt-0.5 text-rose-600 focus:ring-rose-500"
                />
                <div>
                  <span className="font-semibold text-slate-800 dark:text-slate-200">
                    {t('modeReplace')}
                  </span>
                  <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5">
                    Wipes running configuration and completely overrides with new script.
                  </p>
                </div>
              </label>
            </div>

            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pt-2 border-t border-slate-200 dark:border-slate-700 text-xs">
              <label className="flex items-center gap-2 cursor-pointer select-none text-slate-700 dark:text-slate-300">
                <input
                  type="checkbox"
                  checked={enableRollback}
                  onChange={e => setEnableRollback(e.target.checked)}
                  className="rounded text-cyan-500 focus:ring-cyan-500"
                />
                <span className="flex items-center gap-1.5 font-medium">
                  <Clock className="w-3.5 h-3.5 text-cyan-500" />
                  {t('commitConfirmed')}
                </span>
              </label>

              <span className="text-[11px] text-slate-400 font-mono">
                Auto-Backup: Pre-Deploy snapshot will be taken before commit
              </span>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-3.5 bg-slate-50 dark:bg-slate-900 border-t border-slate-200 dark:border-slate-800 flex items-center justify-between">
          <div className="text-xs text-slate-500 dark:text-slate-400 flex items-center gap-1">
            <span>Operator:</span>
            <span className="font-semibold text-slate-800 dark:text-slate-200">
              {currentUser?.name || 'Admin Root'} ({currentUser?.role || 'Admin'})
            </span>
          </div>

          <div className="flex items-center gap-2.5">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl bg-slate-200 dark:bg-slate-800 hover:bg-slate-300 text-slate-700 dark:text-slate-300 font-semibold text-xs transition-colors"
            >
              {t('cancel')}
            </button>

            <button
              type="button"
              disabled={isDeploying || isViewer || !configContent.trim()}
              onClick={handleDeploy}
              className={`px-5 py-2 rounded-xl text-white font-semibold text-xs flex items-center gap-2 shadow-md transition-all ${
                isDeploying
                  ? 'bg-slate-600 cursor-wait'
                  : isViewer
                  ? 'bg-slate-400 cursor-not-allowed opacity-50'
                  : 'bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 shadow-cyan-600/30'
              }`}
            >
              {isDeploying ? (
                <>
                  <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                  <span>Deploying to {currentDevice?.ip}...</span>
                </>
              ) : (
                <>
                  <Upload className="w-3.5 h-3.5" />
                  <span>{t('applyAndDeploy')}</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
