import React, { useState, useEffect, useRef, useMemo } from 'react';
import { useLanguage } from '../../context/LanguageContext';
import { useNetworkData } from '../../context/NetworkDataContext';
import { useAuth } from '../../context/AuthContext';
import { NetworkDevice } from '../../types';
import {
  FileCode2,
  Upload,
  X,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Split,
  FileText,
  RotateCcw,
  Code2,
  Clock,
} from 'lucide-react';

interface ConfigImportModalProps {
  isOpen: boolean;
  onClose: () => void;
  targetDevice?: NetworkDevice | null;
}

// Built-in Enterprise Templates
const SAMPLE_TEMPLATES = {
  cisco_trunk: {
    name: 'Cisco IOS-XE: Enterprise 802.1Q Trunk & Voice VLAN',
    deviceType: 'Switch',
    content: `! Cisco IOS-XE Software Enterprise Switch Template
! Auto-Generated by NetMonitor Configuration Manager
hostname SW-Enterprise-Access
!
vlan 10
 name MGMT-CORP
vlan 20
 name DATA-USERS
vlan 30
 name VOICE-IP
vlan 50
 name WIFI-CORP
!
interface TenGigabitEthernet1/0/1
 description Primary Core Uplink [802.1Q Trunk]
 switchport mode trunk
 switchport trunk allowed vlan 10,20,30,50,70,100
 switchport nonegotiate
 spanning-tree guard root
!
interface range GigabitEthernet1/0/1 - 24
 description User Access Workstation & VoIP Phone
 switchport mode access
 switchport access vlan 20
 switchport voice vlan 30
 spanning-tree portfast
 spanning-tree bpduguard enable
!
end`,
  },
  cisco_ospf: {
    name: 'Cisco IOS-XE: OSPF Routing & WAN Sub-interfaces',
    deviceType: 'Router',
    content: `! Cisco IOS-XE Software WAN Router Template
hostname WAN-Edge-Gateway
!
ip routing
ip domain-lookup
!
interface GigabitEthernet0/0/0
 description Primary ISP Upstream Fiber
 ip address 203.158.0.2 255.255.255.252
 no shutdown
!
interface GigabitEthernet0/0/1
 description LAN Core Transit
 ip address 192.168.100.1 255.255.255.248
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf authentication message-digest
 ip ospf message-digest-key 1 md5 NetMonSecretKey99
 no shutdown
!
router ospf 1
 router-id 192.168.100.1
 passive-interface GigabitEthernet0/0/0
 log-adjacency-changes detail
!
line vty 0 4
 transport input ssh
 logging synchronous
!
end`,
  },
  forti_firewall: {
    name: 'Fortinet FortiOS: NGFW Security Policy & NAT Overload',
    deviceType: 'Firewall',
    content: `# FortiOS Version 7.4.2 Configuration Template
config system global
    set hostname "Perimeter-NGFW-Cluster"
    set timezone 55
end
config system interface
    edit "port1"
        set alias "WAN-Internet"
        set mode static
        set ip 192.168.100.2 255.255.255.248
        set allowaccess ping ssh https
    next
    edit "port2"
        set alias "LAN-Internal"
        set mode static
        set ip 10.10.0.254 255.255.255.0
        set allowaccess ping
    next
end
config firewall policy
    edit 101
        set name "Corp-Users-To-Internet"
        set srcintf "port2"
        set dstintf "port1"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "ALL"
        set utm-status enable
        set ssl-ssh-profile "certificate-inspection"
        set ips-sensor "default"
        set nat enable
    next
end`,
  },
  json_interface: {
    name: 'JSON Format: Interface & Policy Specification',
    deviceType: 'All',
    content: `{
  "schema": "netmonitor.config.v2",
  "device": {
    "hostname": "Core-L3-SW-01",
    "managementIp": "10.10.0.1",
    "snmpCommunity": "public_ro"
  },
  "vlans": [
    { "id": 10, "name": "MGMT", "subnet": "10.10.10.0/24", "gateway": "10.10.10.1" },
    { "id": 20, "name": "CORP-LAN", "subnet": "10.10.20.0/24", "gateway": "10.10.20.1" },
    { "id": 30, "name": "VOIP", "subnet": "10.10.30.0/24", "gateway": "10.10.30.1" },
    { "id": 50, "name": "WIFI-CORP", "subnet": "10.10.50.0/24", "gateway": "10.10.50.1" }
  ],
  "monitoring": {
    "pollingIntervalSeconds": 30,
    "flowExport": "NetFlow-v9",
    "collectorIp": "10.10.100.250"
  }
}`,
  },
};

type ValidationMessage = { type: 'error' | 'warning' | 'info'; text: string; line?: number };
type ValidationResult = { status: 'idle' | 'valid' | 'warning' | 'error'; messages: ValidationMessage[] };

// Syntax & security checks for CLI (Cisco / Fortinet / Aruba) and JSON configs
const validateConfig = (content: string): ValidationResult => {
  const messages: ValidationMessage[] = [];
  let hasError = false;
  let hasWarning = false;

  if (!content.trim()) {
    return { status: 'idle', messages: [] };
  }

  if (content.trim().startsWith('{')) {
    try {
      JSON.parse(content);
      messages.push({ type: 'info', text: 'Valid JSON syntax confirmed. Complies with NetMonitor schema v2.' });
    } catch (err: any) {
      hasError = true;
      messages.push({ type: 'error', text: `JSON Parse Syntax Error: ${err.message}` });
    }
  } else {
    let foundHostname = false;
    let openBlocks = 0;

    content.split('\n').forEach((rawLine, idx) => {
      const line = rawLine.trim();
      const lower = line.toLowerCase();
      const lineNum = idx + 1;

      if (lower.startsWith('hostname ') || lower.startsWith('set hostname')) {
        foundHostname = true;
      }

      if (lower.includes('transport input telnet') || lower.includes('telnet enable')) {
        hasWarning = true;
        messages.push({ type: 'warning', line: lineNum, text: 'Insecure plaintext Telnet protocol detected. Prefer SSHv2.' });
      }

      if (lower.startsWith('password ') && !lower.includes('7 ') && !lower.includes('secret ')) {
        hasWarning = true;
        messages.push({ type: 'warning', line: lineNum, text: 'Plaintext password without encryption hash. Use "enable secret" or "service password-encryption".' });
      }

      if (lower.startsWith('ip http server') && !lower.includes('secure')) {
        hasWarning = true;
        messages.push({ type: 'warning', line: lineNum, text: 'Unencrypted HTTP management enabled. Prefer "ip http secure-server".' });
      }

      const ipMatch = line.match(/\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/g);
      ipMatch?.forEach(ip => {
        if (ip.split('.').map(Number).some(o => o < 0 || o > 255)) {
          hasError = true;
          messages.push({ type: 'error', line: lineNum, text: `Invalid IP address ${ip} (each octet must be 0-255).` });
        }
      });

      // Block balance for FortiOS
      if (line.startsWith('config ') || line.startsWith('edit ')) openBlocks++;
      if (line === 'end' || line === 'next') openBlocks = Math.max(0, openBlocks - 1);
    });

    if (!foundHostname) {
      hasWarning = true;
      messages.push({ type: 'warning', text: 'No "hostname" directive. Device will keep its current name.' });
    }

    if (openBlocks > 0) {
      hasWarning = true;
      messages.push({ type: 'warning', text: `${openBlocks} unclosed configuration block(s) (missing 'end' or 'next').` });
    }
  }

  return { status: hasError ? 'error' : hasWarning ? 'warning' : 'valid', messages };
};

const getRunningConfig = (device?: NetworkDevice) =>
  device
    ? device.config ||
      `! Running configuration for ${device.name} [${device.ip}]\n! Vendor: ${device.vendor} ${device.model}\nhostname ${device.name}\n!\nend`
    : '';

const StepLabel: React.FC<{ step: number; children: React.ReactNode }> = ({ step, children }) => (
  <div className="flex items-center gap-2 text-xs font-bold text-slate-800 dark:text-slate-200">
    <span className="w-5 h-5 rounded-full bg-cyan-600 text-white text-[11px] flex items-center justify-center">{step}</span>
    {children}
  </div>
);

export const ConfigImportModal: React.FC<ConfigImportModalProps> = ({
  isOpen,
  onClose,
  targetDevice,
}) => {
  const { t } = useLanguage();
  const { devices, importDeviceConfig } = useNetworkData();
  const { currentUser, isViewer } = useAuth();

  const [selectedDeviceId, setSelectedDeviceId] = useState<string>('');
  const [configContent, setConfigContent] = useState<string>('');
  const [fileName, setFileName] = useState<string>('');
  const [isDragging, setIsDragging] = useState(false);
  const [activeTab, setActiveTab] = useState<'editor' | 'diff'>('editor');
  const [deploymentMode, setDeploymentMode] = useState<'merge' | 'replace'>('merge');
  const [enableRollback, setEnableRollback] = useState(true);
  const [isDeploying, setIsDeploying] = useState(false);
  const [deploySuccess, setDeploySuccess] = useState(false);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const gutterRef = useRef<HTMLDivElement>(null);

  const currentDevice = devices.find(d => d.id === selectedDeviceId);
  const runningConfig = getRunningConfig(currentDevice);
  const isDirty = configContent !== runningConfig;

  // Start from a clean slate every time the modal opens
  useEffect(() => {
    if (!isOpen) return;
    const device = targetDevice || devices[0];
    setSelectedDeviceId(device?.id || '');
    setConfigContent(getRunningConfig(device));
    setFileName('');
    setActiveTab('editor');
    setDeploymentMode('merge');
    setEnableRollback(true);
    setIsDeploying(false);
    setDeploySuccess(false);
  }, [isOpen, targetDevice]);

  const validation = useMemo(() => validateConfig(configContent), [configContent]);

  // Line-by-line diff between current running config & proposed config
  const { diffLines, addedCount, removedCount } = useMemo(() => {
    const running = (currentDevice?.config || '').split('\n');
    const proposed = configContent.split('\n');
    const runningSet = new Set(running.map(l => l.trim()));
    const proposedSet = new Set(proposed.map(l => l.trim()));

    const lines: { type: 'added' | 'removed' | 'unchanged'; content: string; lineNum?: number }[] = [];

    if (deploymentMode === 'replace') {
      running.forEach((line, idx) => {
        if (line.trim() && !proposedSet.has(line.trim())) {
          lines.push({ type: 'removed', content: line, lineNum: idx + 1 });
        }
      });
    }

    proposed.forEach((line, idx) => {
      const added = line.trim() && !runningSet.has(line.trim());
      lines.push({ type: added ? 'added' : 'unchanged', content: line, lineNum: idx + 1 });
    });

    return {
      diffLines: lines,
      addedCount: lines.filter(d => d.type === 'added').length,
      removedCount: lines.filter(d => d.type === 'removed').length,
    };
  }, [currentDevice, configContent, deploymentMode]);

  if (!isOpen) return null;

  const loadContent = (content: string, name: string) => {
    setConfigContent(content);
    setFileName(name);
    setActiveTab('editor');
  };

  const processFile = (file?: File) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = ev => {
      const text = ev.target?.result as string;
      if (text) loadContent(text, `${file.name} (${(file.size / 1024).toFixed(1)} KB)`);
    };
    reader.readAsText(file);
  };

  const handleDeviceChange = (id: string) => {
    if (isDirty && !confirm(t('cfgConfirmDiscard'))) return;
    setSelectedDeviceId(id);
    loadContent(getRunningConfig(devices.find(d => d.id === id)), '');
  };

  const handleLoadTemplate = (key: string) => {
    const tpl = SAMPLE_TEMPLATES[key as keyof typeof SAMPLE_TEMPLATES];
    if (tpl) loadContent(tpl.content, tpl.name);
  };

  const handleDeploy = () => {
    if (!currentDevice) return;
    if (isViewer) {
      alert('Access Denied: Viewer accounts have read-only privileges.');
      return;
    }
    if (deploymentMode === 'replace' && !confirm(t('cfgConfirmReplace').replace('{name}', currentDevice.name))) {
      return;
    }

    setIsDeploying(true);

    // Simulate connection and checksum transmission
    setTimeout(() => {
      const author = currentUser ? `${currentUser.name} (${currentUser.role})` : 'Operator';
      importDeviceConfig(currentDevice.id, configContent, deploymentMode, enableRollback, author);
      setIsDeploying(false);
      setDeploySuccess(true);
      setTimeout(() => {
        setDeploySuccess(false);
        onClose();
      }, 1800);
    }, 1200);
  };

  const totalLines = configContent ? configContent.split('\n').length : 0;
  const hasChanges = addedCount > 0 || removedCount > 0;
  const canDeploy = !isDeploying && !isViewer && !!currentDevice && configContent.trim() !== '' && validation.status !== 'error' && hasChanges;

  return (
    <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-md z-50 flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl max-w-3xl w-full shadow-2xl overflow-hidden flex flex-col max-h-[92vh]">
        {/* Header */}
        <div className="px-6 py-4 flex items-center justify-between border-b border-slate-200 dark:border-slate-800">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center text-cyan-500">
              <FileCode2 className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-900 dark:text-white">{t('configImportTitle')}</h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">{t('configImportSub')}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Success Alert Banner */}
        {deploySuccess && (
          <div className="p-4 bg-emerald-50 dark:bg-emerald-950/90 border-b border-emerald-300 dark:border-emerald-700 text-emerald-800 dark:text-emerald-200 text-xs flex items-center justify-between">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-emerald-500" />
              <span className="font-semibold">{t('deploySuccess')}</span>
            </div>
            <span className="font-mono text-[11px]">
              {currentDevice?.name} ({currentDevice?.ip})
            </span>
          </div>
        )}

        <div className="p-5 overflow-y-auto space-y-5 flex-1">
          {/* Step 1: Target Device */}
          <section className="space-y-2">
            <StepLabel step={1}>{t('cfgStepDevice')}</StepLabel>
            <select
              value={selectedDeviceId}
              onChange={e => handleDeviceChange(e.target.value)}
              className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl px-3 py-2 text-xs text-slate-900 dark:text-white font-medium focus:outline-none focus:ring-2 focus:ring-cyan-500"
            >
              {devices.map(d => (
                <option key={d.id} value={d.id}>
                  {d.name} — {d.ip} ({d.type})
                </option>
              ))}
            </select>
            {currentDevice && (
              <p className="text-[11px] text-slate-500 dark:text-slate-400 font-mono px-1">
                {currentDevice.vendor} · {currentDevice.model}
              </p>
            )}
          </section>

          {/* Step 2: Config Content */}
          <section className="space-y-2">
            <StepLabel step={2}>{t('cfgStepConfig')}</StepLabel>

            {/* Source toolbar */}
            <div className="flex flex-wrap items-center gap-2">
              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                className="px-3 py-1.5 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-semibold flex items-center gap-1.5"
              >
                <Upload className="w-3.5 h-3.5" />
                {t('cfgUploadFile')}
              </button>
              <input
                ref={fileInputRef}
                type="file"
                accept=".cfg,.txt,.json,.conf,.text"
                onChange={e => {
                  processFile(e.target.files?.[0]);
                  e.target.value = '';
                }}
                className="hidden"
              />

              <select
                value=""
                onChange={e => handleLoadTemplate(e.target.value)}
                className="px-2.5 py-1.5 rounded-lg bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs text-slate-700 dark:text-slate-300 focus:outline-none focus:ring-2 focus:ring-cyan-500"
              >
                <option value="" disabled>
                  {t('cfgTemplatePlaceholder')}
                </option>
                {Object.entries(SAMPLE_TEMPLATES).map(([key, tpl]) => (
                  <option key={key} value={key}>
                    {tpl.name}
                  </option>
                ))}
              </select>

              {isDirty && (
                <button
                  type="button"
                  onClick={() => loadContent(runningConfig, '')}
                  className="px-2.5 py-1.5 rounded-lg text-xs text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 flex items-center gap-1.5"
                >
                  <RotateCcw className="w-3.5 h-3.5" />
                  {t('cfgResetRunning')}
                </button>
              )}

              {fileName && (
                <span className="text-[11px] text-cyan-600 dark:text-cyan-400 flex items-center gap-1 truncate max-w-full">
                  <FileText className="w-3.5 h-3.5 shrink-0" />
                  <span className="truncate">{fileName}</span>
                </span>
              )}
            </div>

            {/* Editor / Diff tabs */}
            <div className="rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden bg-slate-50 dark:bg-slate-950">
              <div className="flex items-center justify-between px-2 py-1.5 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800">
                <div className="flex items-center gap-1">
                  <button
                    type="button"
                    onClick={() => setActiveTab('editor')}
                    className={`px-2.5 py-1 rounded-md text-xs font-semibold flex items-center gap-1.5 ${
                      activeTab === 'editor'
                        ? 'bg-cyan-50 dark:bg-cyan-950/50 text-cyan-700 dark:text-cyan-300'
                        : 'text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800'
                    }`}
                  >
                    <Code2 className="w-3.5 h-3.5" />
                    {t('configEditor')}
                  </button>
                  <button
                    type="button"
                    onClick={() => setActiveTab('diff')}
                    className={`px-2.5 py-1 rounded-md text-xs font-semibold flex items-center gap-1.5 ${
                      activeTab === 'diff'
                        ? 'bg-cyan-50 dark:bg-cyan-950/50 text-cyan-700 dark:text-cyan-300'
                        : 'text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800'
                    }`}
                  >
                    <Split className="w-3.5 h-3.5" />
                    {t('compareDiff')}
                    {hasChanges && (
                      <span className="font-mono text-[10px]">
                        <span className="text-emerald-600 dark:text-emerald-400">+{addedCount}</span>
                        {removedCount > 0 && <span className="text-rose-600 dark:text-rose-400"> -{removedCount}</span>}
                      </span>
                    )}
                  </button>
                </div>
                <span className="text-[11px] text-slate-400 font-mono">
                  {totalLines} {t('cfgLines')}
                </span>
              </div>

              {activeTab === 'editor' ? (
                <div
                  className="relative flex h-72"
                  onDragOver={e => {
                    e.preventDefault();
                    setIsDragging(true);
                  }}
                  onDragLeave={() => setIsDragging(false)}
                  onDrop={e => {
                    e.preventDefault();
                    setIsDragging(false);
                    processFile(e.dataTransfer.files?.[0]);
                  }}
                >
                  {/* Line numbers (scroll-synced with the textarea) */}
                  <div
                    ref={gutterRef}
                    className="w-10 py-3 overflow-hidden bg-slate-100/70 dark:bg-slate-900/60 text-slate-400 dark:text-slate-600 font-mono text-xs select-none text-right pr-2 border-r border-slate-200 dark:border-slate-800"
                  >
                    {Array.from({ length: Math.max(1, totalLines) }).map((_, i) => (
                      <div key={i} className="leading-5">
                        {i + 1}
                      </div>
                    ))}
                  </div>
                  <textarea
                    value={configContent}
                    onChange={e => setConfigContent(e.target.value)}
                    onScroll={e => {
                      if (gutterRef.current) gutterRef.current.scrollTop = e.currentTarget.scrollTop;
                    }}
                    spellCheck={false}
                    placeholder={t('cfgEditorHint')}
                    className="flex-1 bg-transparent text-slate-800 dark:text-emerald-400 font-mono text-xs p-3 focus:outline-none leading-5 resize-none whitespace-pre overflow-auto"
                  />
                  {isDragging && (
                    <div className="absolute inset-0 border-2 border-dashed border-cyan-500 bg-cyan-500/10 rounded-b-xl flex flex-col items-center justify-center gap-1.5 text-cyan-700 dark:text-cyan-300 text-xs font-semibold pointer-events-none">
                      <Upload className="w-5 h-5" />
                      {t('cfgDropHint')}
                    </div>
                  )}
                </div>
              ) : (
                <div className="h-72 overflow-y-auto p-2 space-y-0.5 font-mono text-xs">
                  {!hasChanges ? (
                    <div className="text-slate-500 text-center py-8">{t('cfgNoChanges')}</div>
                  ) : (
                    diffLines.map((line, idx) => (
                      <div
                        key={idx}
                        className={`flex items-start px-2 py-0.5 rounded leading-5 ${
                          line.type === 'added'
                            ? 'bg-emerald-50 dark:bg-emerald-950/50 text-emerald-700 dark:text-emerald-300 border-l-2 border-emerald-500'
                            : line.type === 'removed'
                            ? 'bg-rose-50 dark:bg-rose-950/50 text-rose-700 dark:text-rose-300 border-l-2 border-rose-500'
                            : 'text-slate-500 dark:text-slate-400'
                        }`}
                      >
                        <span className="w-8 select-none text-slate-400 dark:text-slate-600 text-[10px] text-right pr-2">
                          {line.lineNum || ''}
                        </span>
                        <span className="w-4 select-none font-bold">
                          {line.type === 'added' ? '+' : line.type === 'removed' ? '-' : ' '}
                        </span>
                        <span className="flex-1 whitespace-pre-wrap">{line.content}</span>
                      </div>
                    ))
                  )}
                </div>
              )}
            </div>

            {/* Live validation feedback */}
            {validation.status !== 'idle' && (
              <div
                className={`p-3 rounded-xl border text-xs space-y-1.5 ${
                  validation.status === 'valid'
                    ? 'bg-emerald-50 dark:bg-emerald-950/40 border-emerald-300 dark:border-emerald-800 text-emerald-800 dark:text-emerald-300'
                    : validation.status === 'warning'
                    ? 'bg-amber-50 dark:bg-amber-950/40 border-amber-300 dark:border-amber-800 text-amber-800 dark:text-amber-300'
                    : 'bg-rose-50 dark:bg-rose-950/40 border-rose-300 dark:border-rose-800 text-rose-800 dark:text-rose-300'
                }`}
              >
                <div className="flex items-center gap-2 font-semibold">
                  {validation.status === 'valid' ? (
                    <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                  ) : validation.status === 'warning' ? (
                    <AlertTriangle className="w-4 h-4 text-amber-500" />
                  ) : (
                    <XCircle className="w-4 h-4 text-rose-500" />
                  )}
                  <span>
                    {validation.status === 'valid'
                      ? t('syntaxValid')
                      : validation.status === 'warning'
                      ? t('syntaxWarning')
                      : t('syntaxError')}
                  </span>
                </div>
                {validation.status !== 'valid' && (
                  <ul className="list-disc list-inside space-y-0.5 text-[11px] pl-1">
                    {validation.messages
                      .filter(m => m.type !== 'info')
                      .map((m, idx) => (
                        <li key={idx}>
                          {m.line && <span className="font-semibold mr-1">{t('cfgLine')} {m.line}:</span>}
                          {m.text}
                        </li>
                      ))}
                  </ul>
                )}
              </div>
            )}
          </section>

          {/* Step 3: Deployment Strategy */}
          <section className="space-y-2">
            <StepLabel step={3}>{t('cfgStepApply')}</StepLabel>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              <label
                className={`flex items-start gap-2.5 p-3 rounded-xl border cursor-pointer transition-all ${
                  deploymentMode === 'merge'
                    ? 'border-cyan-500 bg-cyan-50 dark:bg-cyan-950/30'
                    : 'border-slate-200 dark:border-slate-700 hover:border-slate-300 dark:hover:border-slate-600'
                }`}
              >
                <input
                  type="radio"
                  name="deployMode"
                  checked={deploymentMode === 'merge'}
                  onChange={() => setDeploymentMode('merge')}
                  className="mt-0.5 text-cyan-600 focus:ring-cyan-500"
                />
                <div>
                  <span className="font-semibold text-slate-800 dark:text-slate-200">{t('modeMerge')}</span>
                  <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5">{t('modeMergeDesc')}</p>
                </div>
              </label>

              <label
                className={`flex items-start gap-2.5 p-3 rounded-xl border cursor-pointer transition-all ${
                  deploymentMode === 'replace'
                    ? 'border-rose-500 bg-rose-50 dark:bg-rose-950/30'
                    : 'border-slate-200 dark:border-slate-700 hover:border-slate-300 dark:hover:border-slate-600'
                }`}
              >
                <input
                  type="radio"
                  name="deployMode"
                  checked={deploymentMode === 'replace'}
                  onChange={() => setDeploymentMode('replace')}
                  className="mt-0.5 text-rose-600 focus:ring-rose-500"
                />
                <div>
                  <span className="font-semibold text-slate-800 dark:text-slate-200">{t('modeReplace')}</span>
                  <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5">{t('modeReplaceDesc')}</p>
                </div>
              </label>
            </div>

            <label className="flex items-center gap-2 cursor-pointer select-none text-xs text-slate-700 dark:text-slate-300 px-1 pt-1">
              <input
                type="checkbox"
                checked={enableRollback}
                onChange={e => setEnableRollback(e.target.checked)}
                className="rounded text-cyan-500 focus:ring-cyan-500"
              />
              <Clock className="w-3.5 h-3.5 text-cyan-500" />
              {t('commitConfirmed')}
            </label>
            <p className="text-[11px] text-slate-400 px-1">{t('cfgAutoBackup')}</p>
          </section>
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-3.5 bg-slate-50 dark:bg-slate-900 border-t border-slate-200 dark:border-slate-800 flex flex-wrap items-center justify-between gap-3">
          <div className="text-xs text-slate-500 dark:text-slate-400 font-mono">
            {t('cfgSummary')}:{' '}
            <span className="text-emerald-600 dark:text-emerald-400 font-semibold">+{addedCount}</span>{' '}
            <span className="text-rose-600 dark:text-rose-400 font-semibold">-{removedCount}</span>
          </div>

          <div className="flex items-center gap-2.5">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl bg-slate-200 dark:bg-slate-800 hover:bg-slate-300 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-semibold text-xs transition-colors"
            >
              {t('cancel')}
            </button>

            <button
              type="button"
              disabled={!canDeploy}
              onClick={handleDeploy}
              className={`px-5 py-2 rounded-xl text-white font-semibold text-xs flex items-center gap-2 transition-all ${
                isDeploying
                  ? 'bg-slate-600 cursor-wait'
                  : !canDeploy
                  ? 'bg-slate-400 dark:bg-slate-700 cursor-not-allowed opacity-60'
                  : deploymentMode === 'replace'
                  ? 'bg-rose-600 hover:bg-rose-500'
                  : 'bg-cyan-600 hover:bg-cyan-500'
              }`}
            >
              {isDeploying ? (
                <>
                  <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                  <span>{t('cfgDeploying')}</span>
                </>
              ) : (
                <>
                  <Upload className="w-3.5 h-3.5" />
                  <span>{t('applyAndDeploy')}</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
